#include "Panels/ComponentGeneratorPanel.h"
#if !defined(TNX_ENABLE_EDITOR)
#error "ComponentGeneratorPanel.cpp requires TNX_ENABLE_EDITOR"
#endif

#include "EditorState.h"
#include "EngineConfig.h"
#include "Logger.h"
#include "imgui.h"

#include <cstdio>
#include <cstring>
#include <filesystem>
#include <fstream>

// ---------------------------------------------------------------------------
// Static lookup tables
// ---------------------------------------------------------------------------

static const char* kFieldTypeNames[] = {
	"float", "int32_t", "uint32_t", "bool", "Fixed32",
};
static constexpr int kNumFieldTypes = 5;

static const char* kTierMacros[] = {
	"TNX_TEMPORAL_FIELDS",
	"TNX_VOLATILE_FIELDS",
	"TNX_REGISTER_FIELDS",
};
static const char* kTierNames[] = { "Temporal", "Volatile", "Cold" };
static constexpr int kNumTiers  = 3;

static const char* kGroupNames[] = { "Render", "Physics", "Logic", "Dual" };
static constexpr int kNumGroups  = 4;

// ---------------------------------------------------------------------------
// Code generation
// ---------------------------------------------------------------------------

void ComponentGeneratorPanel::RegenerateCode()
{
	GeneratedCode.clear();

	if (CompName[0] == '\0')
	{
		GeneratedCode = "// Enter a component name above to generate code.";
		return;
	}

	bool isCold = (TierIndex == 2);

	std::string out;
	out += "#pragma once\n";
	out += "#include \"FieldProxy.h\"\n";
	out += "#include \"SchemaValidation.h\"\n";
	out += "\n";
	out += "// Auto-generated by Trinyx Component Generator — edit with care.\n";
	out += std::string("// Tier:  ") + kTierNames[TierIndex] + "\n";
	if (!isCold)
		out += std::string("// Group: ") + kGroupNames[GroupIndex] + "\n";
	out += "\n";

	// Macro invocation — Cold tier does not take a SystemGroup parameter.
	out += kTierMacros[TierIndex];
	out += "(";
	out += CompName;
	if (!isCold)
	{
		out += ", SystemGroup::";
		out += kGroupNames[GroupIndex];
	}
	for (const auto& f : Fields)
	{
		if (f.Name[0] == '\0') continue;
		out += ", ";
		out += f.Name;
	}
	out += ");\n\n";

	// Struct body
	out += "struct ";
	out += CompName;
	out += "\n{\n";

	for (const auto& f : Fields)
	{
		if (f.Name[0] == '\0') continue;
		out += "    FieldProxy<";
		out += kFieldTypeNames[f.TypeIndex];
		out += "> ";
		out += f.Name;
		out += ";\n";
	}

	out += "\n    static void DefineFields()\n    {\n";
	for (const auto& f : Fields)
	{
		if (f.Name[0] == '\0') continue;
		out += "        Bind(&";
		out += CompName;
		out += "::";
		out += f.Name;
		out += ");\n";
	}
	out += "    }\n";
	out += "};\n";

	GeneratedCode = std::move(out);
}

bool ComponentGeneratorPanel::ExportToFile()
{
	if (OutputPath[0] == '\0')
	{
		snprintf(StatusMessage, sizeof(StatusMessage), "Set an output path before exporting.");
		bStatusError = true;
		return false;
	}
	if (CompName[0] == '\0')
	{
		snprintf(StatusMessage, sizeof(StatusMessage), "Enter a component name before exporting.");
		bStatusError = true;
		return false;
	}

	try
	{
		std::filesystem::create_directories(std::filesystem::path(OutputPath).parent_path());
	}
	catch (const std::exception& ex)
	{
		snprintf(StatusMessage, sizeof(StatusMessage), "Failed to create output directory: %s", ex.what());
		bStatusError = true;
		LOG_ERROR_F("[ComponentGenerator] Failed to create output directory: %s", ex.what());
		return false;
	}

	std::ofstream file(OutputPath);
	if (!file.is_open())
	{
		snprintf(StatusMessage, sizeof(StatusMessage), "Failed to open: %s", OutputPath);
		bStatusError = true;
		return false;
	}

	file << GeneratedCode;
	snprintf(StatusMessage, sizeof(StatusMessage), "Exported: %s", OutputPath);
	bStatusError = false;
	LOG_INFO_F("[ComponentGenerator] Exported '%s' -> %s", CompName, OutputPath);
	return true;
}

// ---------------------------------------------------------------------------
// Draw
// ---------------------------------------------------------------------------

void ComponentGeneratorPanel::Draw(EditorState& state)
{
	ImGui::Begin(Title, &bVisible);

	bool changed = false;

	// --- Component name ---
	ImGui::Text("Component Name:");
	ImGui::SameLine();
	ImGui::SetNextItemWidth(200.0f);
	if (ImGui::InputText("##CompName", CompName, sizeof(CompName)))
	{
		changed = true;
		// Auto-suggest output path when a project directory is configured.
		if (state.ConfigPtr && state.ConfigPtr->ProjectDir[0] != '\0' && OutputPath[0] == '\0')
		{
			snprintf(OutputPath, sizeof(OutputPath),
					 "%s/src/Runtime/Components/Public/%s.h",
					 state.ConfigPtr->ProjectDir, CompName);
		}
	}

	// --- Storage tier ---
	ImGui::Text("Storage Tier:  ");
	ImGui::SameLine();
	ImGui::SetNextItemWidth(120.0f);
	if (ImGui::Combo("##Tier", &TierIndex, kTierNames, kNumTiers)) changed = true;

	// System group is only meaningful for Temporal / Volatile tiers.
	if (TierIndex < 2)
	{
		ImGui::Text("System Group: ");
		ImGui::SameLine();
		ImGui::SetNextItemWidth(120.0f);
		if (ImGui::Combo("##Group", &GroupIndex, kGroupNames, kNumGroups)) changed = true;
	}

	// --- Field list ---
	ImGui::Separator();
	ImGui::Text("Fields");
	ImGui::SameLine();
	if (ImGui::SmallButton("+##AddField"))
	{
		Fields.push_back({});
		changed = true;
	}
	ImGui::SameLine();
	ImGui::TextDisabled("(FieldProxy<T> — registered in DefineFields)");

	for (int i = 0; i < static_cast<int>(Fields.size()); i++)
	{
		auto& f = Fields[static_cast<size_t>(i)];
		ImGui::PushID(i);

		ImGui::SetNextItemWidth(160.0f);
		if (ImGui::InputText("##FName", f.Name, sizeof(f.Name))) changed = true;
		ImGui::SameLine();
		ImGui::SetNextItemWidth(100.0f);
		if (ImGui::Combo("##FType", &f.TypeIndex, kFieldTypeNames, kNumFieldTypes)) changed = true;
		ImGui::SameLine();
		if (ImGui::SmallButton("x"))
		{
			Fields.erase(Fields.begin() + i);
			changed = true;
			ImGui::PopID();
			break;
		}

		ImGui::PopID();
	}

	// --- Output path + Export ---
	ImGui::Separator();
	ImGui::Text("Output Path:");
	ImGui::SetNextItemWidth(-90.0f);
	ImGui::InputText("##OutPath", OutputPath, sizeof(OutputPath));
	ImGui::SameLine();
	if (ImGui::Button("Export##Exp", ImVec2(80.0f, 0.0f)))
	{
		RegenerateCode();
		ExportToFile();
	}

	if (StatusMessage[0] != '\0')
	{
		ImVec4 col = bStatusError ? ImVec4(1.0f, 0.35f, 0.35f, 1.0f) : ImVec4(0.35f, 1.0f, 0.35f, 1.0f);
		ImGui::TextColored(col, "%s", StatusMessage);
	}

	// --- Generated code preview ---
	ImGui::Separator();
	ImGui::Text("Generated Code:");

	if (changed) RegenerateCode();

	ImGui::BeginChild("##CodePreview", ImVec2(0.0f, 0.0f), ImGuiChildFlags_None,
					  ImGuiWindowFlags_HorizontalScrollbar);
	ImGui::TextUnformatted(GeneratedCode.c_str());
	ImGui::EndChild();

	ImGui::End();
}
