#include "Panels/ComponentGeneratorPanel.h"
#if !defined(TNX_ENABLE_EDITOR)
#error "ComponentGeneratorPanel.cpp requires TNX_ENABLE_EDITOR"
#endif

#include "EditorState.h"
#include "EngineConfig.h"
#include "Logger.h"
#include "ReflectionRegistry.h"
#include "ScriptRegistry.h"
#include "TnxStyle.h"
#include "TnxWidgets.h"
#include "imgui.h"

#include <cstdio>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <string>
#include <vector>

// ---------------------------------------------------------------------------
// Static lookup tables
// ---------------------------------------------------------------------------

static const char* FieldTypeNames[] = {
	"SimFloat",
	"int32_t",
	"uint32_t",
	"bool",
};
static constexpr int NumFieldTypes = 4;

// Proxy type alias for each field type (template param WIDTH implied).
static const char* FieldProxyNames[] = {
	"FloatProxy",
	"IntProxy",
	"UIntProxy",
	"UIntProxy",
};

static const char* TierMacros[] = {
	"TNX_TEMPORAL_FIELDS",
	"TNX_VOLATILE_FIELDS",
	"TNX_REGISTER_FIELDS",
};
static const char* TierNames[] = { "Temporal", "Volatile", "Cold" };
static constexpr int NumTiers  = 3;

static const char* GroupNames[] = { "Render", "Physics", "Logic", "Dual" };
static constexpr int NumGroups  = 4;

static const ScriptFieldType TypeIndexToScript[] = {
	ScriptFieldType::Float,  // SimFloat
	ScriptFieldType::Int32,  // int32_t
	ScriptFieldType::UInt32, // uint32_t
	ScriptFieldType::Bool,   // bool
};
static const SystemID GroupIndexToSysID[] = {
	SystemID::Render,
	SystemID::Physics,
	SystemID::Logic,
	SystemID::Dual,
};
static const CacheTier TierIndexToCacheTier[] = {
	CacheTier::Temporal,
	CacheTier::Volatile,
	CacheTier::Volatile,
};

// ---------------------------------------------------------------------------
// Name validation
// ---------------------------------------------------------------------------

void ComponentGeneratorPanel::ValidateName()
{
	CompName   = TnxName(CompNameBuf);
	bNameTaken = false;

	if (!CompName.IsValid()) return;

	// Check compile-time components registered at static init.
	const auto& nameMap = ReflectionRegistry::Get().NameToComponentID;
	if (nameMap.count(CompNameBuf))
	{
		bNameTaken = true;
		return;
	}

	// Check runtime script components registered this session.
	if (ScriptRegistry::Get().GetSchema(CompNameBuf))
		bNameTaken = true;
}

// ---------------------------------------------------------------------------
// Code generation
// ---------------------------------------------------------------------------

void ComponentGeneratorPanel::RegenerateCode()
{
	GeneratedCode.clear();

	if (!CompName.IsValid())
	{
		GeneratedCode = "// Enter a component name above to generate code.";
		return;
	}

	const char* name = CompName.GetStr();

	bool isCold          = (TierIndex == 2);
	bool isNetReplicated = (bReplicated && TierIndex == 0);

	std::string out;
	out += "#pragma once\n";
	out += "#include <FieldProxy.h>\n";
	out += "#include \"ComponentView.h\"\n";
	out += "#include \"SchemaReflector.h\"\n";
	if (isNetReplicated)
		out += "#include \"NetDelta.h\"\n";
	out += "\n";
	out += "// Auto-generated by Trinyx Component Generator — edit with care.\n";
	out += std::string("// Tier:  ") + TierNames[TierIndex] + "\n";
	if (!isCold)
		out += std::string("// Group: ") + GroupNames[GroupIndex] + "\n";
	out += "\n";

	// Template header + CRTP base
	out += "template <FieldWidth WIDTH = FieldWidth::Scalar>\n";
	out += std::string("struct ") + name + " : ComponentView<" + name + ", WIDTH>\n";
	out += "{\n";

	// Registration macro — Cold uses TNX_REGISTER_FIELDS (no group argument)
	out += "    ";
	out += TierMacros[TierIndex];
	out += "(";
	out += name;
	if (!isCold)
	{
		out += ", ";
		out += GroupNames[GroupIndex];
	}
	for (const auto& f : Fields)
	{
		if (f.Name[0] == '\0') continue;
		out += ", ";
		out += f.Name;
	}
	out += ")\n";

	// Field declarations
	if (!Fields.empty())
	{
		out += "\n";
		for (const auto& f : Fields)
		{
			if (f.Name[0] == '\0') continue;
			out += "    ";
			out += FieldProxyNames[f.TypeIndex];
			out += "<WIDTH> ";
			out += f.Name;
			out += ";\n";
		}
	}

	out += "};\n\n";
	out += std::string("TNX_REGISTER_COMPONENT(") + name + ")\n";

	if (isNetReplicated)
		out += std::string("TNX_NET_TEMPORAL(") + name + ")\n";

	GeneratedCode = std::move(out);
}

bool ComponentGeneratorPanel::ExportToFile()
{
	if (OutputPath[0] == '\0')
	{
		snprintf(StatusMessage, sizeof(StatusMessage), "Set an output path before exporting.");
		bStatusError = true;
		return false;
	}
	if (!CompName.IsValid())
	{
		snprintf(StatusMessage, sizeof(StatusMessage), "Enter a component name before exporting.");
		bStatusError = true;
		return false;
	}

	try
	{
		std::filesystem::create_directories(std::filesystem::path(OutputPath).parent_path());
	}
	catch (const std::exception& ex)
	{
		snprintf(StatusMessage, sizeof(StatusMessage), "Failed to create output directory: %s", ex.what());
		bStatusError = true;
		LOG_ENG_ERROR_F("[ComponentGenerator] Failed to create output directory: %s", ex.what());
		return false;
	}

	std::ofstream file(OutputPath);
	if (!file.is_open())
	{
		snprintf(StatusMessage, sizeof(StatusMessage), "Failed to open: %s", OutputPath);
		bStatusError = true;
		return false;
	}

	file << GeneratedCode;
	{
		const std::string s = std::string("Exported: ") + OutputPath;
		strncpy(StatusMessage, s.c_str(), sizeof(StatusMessage) - 1);
		StatusMessage[sizeof(StatusMessage) - 1] = '\0';
		LOG_ENG_INFO(s.c_str());
	}
	bStatusError = false;
	LOG_ENG_INFO_F("[ComponentGenerator] Exported '%s'", CompName.GetStr());
	return true;
}

void ComponentGeneratorPanel::RegisterAsScript()
{
	if (!CompName.IsValid())
	{
		snprintf(StatusMessage, sizeof(StatusMessage), "Enter a component name before registering.");
		bStatusError = true;
		return;
	}

	const char* name = CompName.GetStr();
	SystemID sysID   = (TierIndex < 2) ? GroupIndexToSysID[GroupIndex] : SystemID::None;
	CacheTier tier   = TierIndexToCacheTier[TierIndex];

	std::vector<ScriptFieldType> types;
	std::vector<const char*> fieldNames;
	for (const auto& f : Fields)
	{
		if (f.Name[0] == '\0') continue;
		types.push_back(TypeIndexToScript[f.TypeIndex]);
		fieldNames.push_back(f.Name);
	}

	bool breakingChange = false;
	ComponentTypeID id  = ScriptRegistry::Get().RegisterOrUpdate(
		name, sysID, tier,
		types.data(), fieldNames.data(), static_cast<uint8_t>(types.size()),
		&breakingChange);

	if (breakingChange)
	{
		snprintf(StatusMessage, sizeof(StatusMessage),
			"[S] Breaking change on '%s' — fields removed or reordered. "
			"Stop PIE to re-register.",
			name);
		bStatusError = true;
	}
	else if (id == 0)
	{
		snprintf(StatusMessage, sizeof(StatusMessage), "Failed to register '%s'.", name);
		bStatusError = true;
	}
	else
	{
		snprintf(StatusMessage, sizeof(StatusMessage),
			"[S] '%s' live (TypeID %u, %u fields) — AoS storage, no SIMD, no rollback. "
			"Export .h when stable.",
			name, id, static_cast<unsigned>(types.size()));
		bStatusError = false;
	}
}

// ---------------------------------------------------------------------------
// Draw
// ---------------------------------------------------------------------------

void ComponentGeneratorPanel::Draw(EditorState& state)
{
	if (!BeginPadded())
	{
		ImGui::End();
		return;
	}
	TnxWidgets::PanelHeader(nullptr, "Component Generator");

	bool changed = false;

	// --- Component name ---
	ImGui::Text("Component Name:");
	ImGui::SameLine();
	ImGui::SetNextItemWidth(200.0f);
	if (ImGui::InputText("##CompName", CompNameBuf, sizeof(CompNameBuf)))
	{
		ValidateName();
		changed = true;
		if (!bNameTaken && state.ConfigPtr && state.ConfigPtr->ProjectDir[0] != '\0' && OutputPath[0] == '\0')
		{
			std::string suggested = std::string(state.ConfigPtr->ProjectDir)
									+ "/src/Runtime/Components/Public/" + CompName.GetStr() + ".h";
			snprintf(OutputPath, sizeof(OutputPath), "%s", suggested.c_str());
		}
	}
	if (bNameTaken)
	{
		ImGui::SameLine();
		ImGui::PushStyleColor(ImGuiCol_Text, ImVec4(1.0f, 0.4f, 0.4f, 1.0f));
		ImGui::TextUnformatted("Name already registered");
		ImGui::PopStyleColor();
	}

	// --- Storage tier ---
	ImGui::Text("Storage Tier:  ");
	ImGui::SameLine();
	ImGui::SetNextItemWidth(120.0f);
	if (ImGui::Combo("##Tier", &TierIndex, TierNames, NumTiers)) changed = true;

	if (TierIndex < 2)
	{
		ImGui::Text("System Group: ");
		ImGui::SameLine();
		ImGui::SetNextItemWidth(120.0f);
		if (ImGui::Combo("##Group", &GroupIndex, GroupNames, NumGroups)) changed = true;
	}

	{
		ImGui::PushStyleColor(ImGuiCol_Text, TierIndex == 0 ? TnxStyle::Color::Fg : TnxStyle::Color::FgDim);
		if (ImGui::Checkbox("Replicated (net)##rep", &bReplicated))
		{
			if (TierIndex != 0) bReplicated = false;
			changed = true;
		}
		ImGui::PopStyleColor();
		if (TierIndex != 0)
		{
			ImGui::SameLine(0, 6);
			ImGui::PushStyleColor(ImGuiCol_Text, TnxStyle::Color::FgDim);
			ImGui::TextUnformatted("(Temporal only)");
			ImGui::PopStyleColor();
		}
	}

	// --- Field list ---
	ImGui::Separator();
	ImGui::Text("Fields");
	ImGui::SameLine();
	if (ImGui::SmallButton("+##AddField"))
	{
		Fields.push_back({});
		changed = true;
	}

	for (int i = 0; i < static_cast<int>(Fields.size()); i++)
	{
		auto& f = Fields[static_cast<size_t>(i)];
		ImGui::PushID(i);

		ImGui::SetNextItemWidth(160.0f);
		if (ImGui::InputText("##FName", f.Name, sizeof(f.Name))) changed = true;
		ImGui::SameLine();
		ImGui::SetNextItemWidth(100.0f);
		if (ImGui::Combo("##FType", &f.TypeIndex, FieldTypeNames, NumFieldTypes)) changed = true;
		ImGui::SameLine();
		if (ImGui::SmallButton("x"))
		{
			Fields.erase(Fields.begin() + i);
			changed = true;
			ImGui::PopID();
			break;
		}

		ImGui::PopID();
	}

	// --- Actions ---
	ImGui::Separator();

	ImGui::Text("Output Path:");
	ImGui::SetNextItemWidth(-90.0f);
	ImGui::InputText("##OutPath", OutputPath, sizeof(OutputPath));
	ImGui::SameLine();
	if (bNameTaken) ImGui::BeginDisabled();
	if (ImGui::Button("Export .h##Exp", ImVec2(80.0f, 0.0f)))
	{
		RegenerateCode();
		ExportToFile();
	}
	if (bNameTaken) ImGui::EndDisabled();

	ImGui::SetCursorPosY(ImGui::GetCursorPosY() + 2);
	if (bNameTaken) ImGui::BeginDisabled();
	if (ImGui::Button("Register Script [S]##Reg", ImVec2(-1.0f, 0.0f)))
		RegisterAsScript();
	if (bNameTaken) ImGui::EndDisabled();

	if (StatusMessage[0] != '\0')
	{
		ImVec4 col = bStatusError ? ImVec4(1.0f, 0.35f, 0.35f, 1.0f) : ImVec4(0.35f, 1.0f, 0.35f, 1.0f);
		ImGui::TextColored(col, "%s", StatusMessage);
	}

	// --- Generated code preview ---
	ImGui::Separator();
	ImGui::Text("Generated Code:");

	if (changed) RegenerateCode();

	ImGui::BeginChild("##CodePreview", ImVec2(0.0f, 0.0f), ImGuiChildFlags_None,
		ImGuiWindowFlags_HorizontalScrollbar);
	ImGui::TextUnformatted(GeneratedCode.c_str());
	ImGui::EndChild();

	ImGui::End();
}
