#include "Soul.h"

#include "FlowManager.h"
#include "NetConnectionManager.h"
#include "ReflectionRegistry.h"

// ---------------------------------------------------------------------------
// Soul.cpp — engine-reserved SoulRPC implementations + dispatch.
//
// Engine-reserved MethodIDs [0, 127] are claimed here via the TNX_IMPL_*
// registrars that run at static init time. Because Soul.cpp is linked before
// any game TU, these IDs are assigned first in practice. Deterministic baking
// will enforce the ordering correctly when it lands.
//
// Game-defined RPCs live in the user's Soul subclass .cpp files and claim
// IDs from the user band [128+].
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// DispatchServerRPC / DispatchClientRPC
// ---------------------------------------------------------------------------

void Soul::DispatchServerRPC(const RPCContext& ctx, const RPCHeader& hdr, const uint8_t* params)
{
	// Refresh channel from the connection that sent this packet so reply
	// thunks called inside the handler route back to the right client.
	Channel = NetChannel(ctx.CI, ctx.Mgr);
	ReflectionRegistry::Get().DispatchServerRPC(this, ctx, hdr, params);
}

void Soul::DispatchClientRPC(const RPCContext& ctx, const RPCHeader& hdr, const uint8_t* params)
{
	// On the client there is typically one connection (to the server), but
	// refresh the channel for symmetry and forward-compat.
	Channel = NetChannel(ctx.CI, ctx.Mgr);
	ReflectionRegistry::Get().DispatchClientRPC(this, ctx, hdr, params);
}

// ---------------------------------------------------------------------------
// PlayerBegin — engine-reserved, MethodID 0
//
// Client thunk: Soul::PlayerBegin(const PlayerBeginRequestPayload&)
//   Generated by TNX_IMPL_SERVER. Serialises RPCHeader + payload → server.
//
// Server handler: Soul::PlayerBegin(const RPCContext&, const PlayerBeginRequestPayload&)
//   Replaces the game-layer logic that was in ServerNetThread's PlayerBeginRequest
//   case. RepState gate lives here; GameMode is reached via FlowManager.
// ---------------------------------------------------------------------------
TNX_IMPL_SERVER(Soul, PlayerBegin, PlayerBeginRequestPayload)
{
	if (!ctx.CI)
	{
		LOG_WARN("[Soul] PlayerBegin: no ConnectionInfo in ctx");
		return;
	}

	if (ctx.CI->RepState != ClientRepState::Loaded)
	{
		PlayerBeginRejectPayload reject{};
		reject.PredictionID = params.PredictionID;
		reject.Reason       = 1; // Wrong RepState
		PlayerBeginReject(reject);
		return;
	}

	const auto result = FlowMgr
		? FlowMgr->HandlePlayerBeginRequest(this, params)
		: std::nullopt;

	if (result.has_value())
	{
		PlayerBeginConfirmPayload confirm{};
		confirm.PredictionID = params.PredictionID;
		confirm.NetHandle    = 0;
		confirm.Generation   = 0;
		confirm.PosX         = result->PosX;
		confirm.PosY         = result->PosY;
		confirm.PosZ         = result->PosZ;
		ctx.CI->RepState = ClientRepState::Playing;
		PlayerBeginConfirm(confirm);
		LOG_INFO_F("[Soul] PlayerBeginConfirm sent (ownerID=%u, pos=%.1f,%.1f,%.1f)",
		           OwnerID, confirm.PosX, confirm.PosY, confirm.PosZ);
	}
	else
	{
		PlayerBeginRejectPayload reject{};
		reject.PredictionID = params.PredictionID;
		reject.Reason       = 2; // GameMode rejected
		PlayerBeginReject(reject);
		LOG_INFO_F("[Soul] PlayerBeginReject sent (ownerID=%u)", OwnerID);
	}
}

// ---------------------------------------------------------------------------
// PlayerBeginConfirm — engine-reserved, MethodID 1
//
// Server thunk: Soul::PlayerBeginConfirm(const PlayerBeginConfirmPayload&)
//   Generated by TNX_IMPL_CLIENT. Called from the PlayerBegin server handler
//   above; routes back to the originating client.
//
// Client handler: Soul::PlayerBeginConfirm(const RPCContext&, const PlayerBeginConfirmPayload&)
//   Clears the prediction ledger entry, advances RepState, and posts the
//   PlayerBeginConfirm FlowEvent so the active FlowState can wire the Body.
// ---------------------------------------------------------------------------
TNX_IMPL_CLIENT(Soul, PlayerBeginConfirm, PlayerBeginConfirmPayload)
{
	if (ctx.CI)
	{
		ctx.CI->Predictions.Clear(params.PredictionID);
		ctx.CI->RepState = ClientRepState::Playing;
	}

	if (FlowMgr)
	{
		FlowMgr->PostPlayerBeginConfirm(params);
		// Ensure client-side Soul is in the Souls table. OnClientLoaded guards
		// against double-create so calling it here is safe and idempotent.
		FlowMgr->OnClientLoaded(OwnerID);
	}

	LOG_INFO_F("[Soul] PlayerBeginConfirm received (PredictionID=%u, pos=%.1f,%.1f,%.1f)",
	           params.PredictionID, params.PosX, params.PosY, params.PosZ);
}

// ---------------------------------------------------------------------------
// PlayerBeginReject — engine-reserved, MethodID 2
//
// Server thunk: Soul::PlayerBeginReject(const PlayerBeginRejectPayload&)
//   Generated by TNX_IMPL_CLIENT. Called from the PlayerBegin server handler
//   when the GameMode rejects or RepState gate fires.
//
// Client handler: Soul::PlayerBeginReject(const RPCContext&, const PlayerBeginRejectPayload&)
//   Clears the prediction ledger entry and posts the PlayerBeginReject FlowEvent.
// ---------------------------------------------------------------------------
TNX_IMPL_CLIENT(Soul, PlayerBeginReject, PlayerBeginRejectPayload)
{
	if (ctx.CI)
		ctx.CI->Predictions.Clear(params.PredictionID);

	if (FlowMgr)
		FlowMgr->PostNetEvent(static_cast<uint8_t>(FlowEventID::PlayerBeginReject));

	LOG_WARN_F("[Soul] PlayerBeginReject received (PredictionID=%u, reason=%u)",
	           params.PredictionID, params.Reason);
}
