#!/usr/bin/env python3
"""Generate FixedTrig.h with a 1024-entry sin LUT for [0, π/2]"""

import math
import os

SCALE = 1048576  # Must match Fixed32::Scale
N = 1024
PI_2 = 1.5707963267948966

values = []
for i in range(N):
    angle = (i + 0.5) / N * PI_2  # center of bin, avoids precision loss
    sin_val = math.sin(angle)
    fixed = int(sin_val * SCALE + 0.5)
    values.append(fixed)

# Write the array in a single block of lines for clarity.
# Use a static_assert to catch size mismatches at compile time.
output = f'''// Auto-generated by Tools/GenerateFixedTrigLUT.py
// Do not edit manually. Regenerate when Fixed32::Scale changes.

#pragma once
#include <cstdint>
#include "Fixed32.h"

namespace FixedTrigDetail {{
    static constexpr int32_t kSinLUT[{N}] = {{
'''

# Write 8 entries per line for readability
for i in range(0, N, 8):
    line = ', '.join(f'{values[j]:7d}' for j in range(i, min(i + 8, N)))
    output += '        ' + line + ',\n'

output += f'''    }};
    static_assert(sizeof(kSinLUT) / sizeof(kSinLUT[0]) == {N}, "LUT size mismatch");
}}

// Reduced to [0, π/2] by caller.
FORCE_INLINE Fixed32 FixedSinInternal(Fixed32 angle, Fixed32 fraction, uint32_t index)
{{
    const auto* lut = FixedTrigDetail::kSinLUT;
    int32_t v0 = lut[index];
    int32_t v1 = lut[index + 1];
    int32_t diff = v1 - v0;
    int64_t result = v0 + (static_cast<int64_t>(diff) * fraction.value / Fixed32::Scale);
    return Fixed32::FromRaw(static_cast<int32_t>(result));
}}
'''

# Append the rest of the file (ReduceAngle, FixedSin, FixedCos) – reuse your existing code.
# I'll reproduce the exact structure from your current FixedTrig.h after the LUT definition.
# Copy the following text exactly (it's the same as your current file from "struct ReducedAngle" onward).

output += '''
// Reduce angle to [0, π/2], return quadrant 0-3.
struct ReducedAngle {
    Fixed32 angle;
    int32_t quadrant;
};

FORCE_INLINE ReducedAngle ReduceAngle(Fixed32 x)
{
    static constexpr Fixed32 kPI_2 = Fixed32::FromDouble(1.5707963267948966);
    // Compute quadrant = floor(x / kPI_2) via integer division of raw values
    Fixed32 ratio = x / kPI_2;
    int32_t q = ratio.value / Fixed32::Scale;
    if (q < 0) q = 0;
    if (q > 3) q = 3;
    ReducedAngle r;
    r.quadrant = q;
    Fixed32 quadrantAngle = kPI_2 * Fixed32::FromInt(q);
    r.angle = x - quadrantAngle;
    if (r.angle < Fixed32(0)) r.angle = Fixed32(0);
    if (r.angle > kPI_2) r.angle = kPI_2;
    return r;
}

FORCE_INLINE Fixed32 FixedSin(Fixed32 x)
{
    auto red = ReduceAngle(x);
    static constexpr Fixed32 kPI_2 = Fixed32::FromDouble(1.5707963267948966);
    static constexpr int32_t N = 1024;
    static constexpr Fixed32 kStep = Fixed32::FromDouble(kPI_2.ToDouble() / N);

    Fixed32 baseAngle;
    bool negate = false;
    if (red.quadrant == 0) {
        baseAngle = red.angle;
        negate = false;
    } else if (red.quadrant == 1) {
        baseAngle = kPI_2 - red.angle;
        negate = false;
    } else if (red.quadrant == 2) {
        baseAngle = red.angle;
        negate = true;
    } else { // quadrant==3
        baseAngle = kPI_2 - red.angle;
        negate = true;
    }
    int32_t index = static_cast<int32_t>(baseAngle.value / kStep.value);
    if (index >= N - 1) index = N - 2;
    Fixed32 fraction = (baseAngle - kStep * Fixed32::FromInt(index)) / kStep;
    Fixed32 sinVal = FixedSinInternal(baseAngle, fraction, index);
    return negate ? -sinVal : sinVal;
}

FORCE_INLINE Fixed32 FixedCos(Fixed32 x)
{
    static constexpr Fixed32 kPI_2 = Fixed32::FromDouble(1.5707963267948966);
    return FixedSin(kPI_2 - x);
}
'''

output_path = 'src/Runtime/Math/Public/FixedTrig.h'
os.makedirs(os.path.dirname(output_path), exist_ok=True)
with open(output_path, 'w') as f:
    f.write(output)
print(f"Generated {output_path} with {N} entries")
