#!/usr/bin/env python3
"""Generate FixedTrig.h with a 1024-entry sin LUT for [0, π/2]"""

import math
import os

SCALE = 1048576  # Must match FixedUnit::Scale (= FixedUnitsPerRadian)
N = 1024  # number of bins; table has N+1 entries covering [0, π/2] inclusive
PI_2 = 1.5707963267948966

# Endpoint sampling: kSinLUT[i] = sin(i/N * π/2).
# kSinLUT[0] = 0 exactly; kSinLUT[N] = 1048576 exactly.
# The interpolation path uses lut[index] and lut[index+1] (index ∈ [0, N-1]).
values = []
for i in range(N + 1):
    angle = i / N * PI_2
    sin_val = math.sin(angle)
    fixed = int(sin_val * SCALE + 0.5)
    values.append(fixed)

lines = [
    "// Auto-generated by Tools/GenerateFixedTrigLUT.py",
    "// Do not edit manually. Regenerate when FixedUnit::Scale changes.",
    "",
    "#pragma once",
    "#include <cstdint>",
    "",
    "#ifndef FORCE_INLINE",
    "#  ifdef _MSC_VER",
    "#    define FORCE_INLINE __forceinline",
    "#  else",
    "#    define FORCE_INLINE inline __attribute__((always_inline))",
    "#  endif",
    "#endif",
    "",
    '#include "Fixed32.h"',
    "",
    "namespace FixedTrigDetail",
    "{",
    f"    static constexpr int32_t kSinLUT[{N + 1}] = {{",
]

for i in range(0, N + 1, 8):
    chunk = [values[j] for j in range(i, min(i + 8, N + 1))]
    lines.append("        " + ", ".join(f"{v:7d}" for v in chunk) + ",")

lines += [
    "    };",
    f'    static_assert(sizeof(kSinLUT) / sizeof(kSinLUT[0]) == {N + 1}, "LUT size mismatch");',
    "}",
    "",
    "// Reduce arbitrary Fixed32 angle to [0, π/2] + quadrant 0-3.",
    "struct ReducedAngle",
    "{",
    "    Fixed32 angle;",
    "    int32_t quadrant;",
    "};",
    "",
    "FORCE_INLINE ReducedAngle ReduceAngle(Fixed32 x)",
    "{",
    "    static constexpr Fixed32 kPI_2 = Fixed32::FromDouble(1.5707963267948966);",
    "    const int64_t xv    = static_cast<int64_t>(x.value);",
    "    const int64_t pv    = static_cast<int64_t>(kPI_2.value);",
    "    int64_t       q_raw = xv / pv;",
    "    if (xv % pv < 0) --q_raw;  // floor-division for negative angles",
    "    const int32_t q = static_cast<int32_t>(((q_raw % 4) + 4) % 4);",
    "    int64_t rem = xv - q_raw * pv;",
    "    if (rem < 0)  rem = 0;",
    "    if (rem > pv) rem = pv;",
    "    ReducedAngle r;",
    "    r.quadrant = q;",
    "    r.angle    = Fixed32::FromRaw(static_cast<int32_t>(rem));",
    "    return r;",
    "}",
    "",
    "// Interpolate sin LUT at fraction ∈ [0, 1) within bin [index, index+1].",
    "// fraction is a Fixed32 in [0, Scale); index ∈ [0, N-2].",
    "FORCE_INLINE FixedUnit FixedSinInternal(Fixed32 fraction, uint32_t index)",
    "{",
    "    const int32_t v0     = FixedTrigDetail::kSinLUT[index];",
    "    const int32_t v1     = FixedTrigDetail::kSinLUT[index + 1];",
    "    const int32_t diff   = v1 - v0;",
    "    const int64_t result = static_cast<int64_t>(v0) +",
    "                           (static_cast<int64_t>(diff) * fraction.value / Fixed32::Scale64);",
    "    return FixedUnit::FromRaw(static_cast<int32_t>(result));",
    "}",
    "",
    "FORCE_INLINE FixedUnit FixedSin(Fixed32 x)",
    "{",
    "    static constexpr Fixed32 kPI_2 = Fixed32::FromDouble(1.5707963267948966);",
    "    static constexpr int32_t kN    = 1024;",
    "",
    "    const auto red = ReduceAngle(x);",
    "",
    "    Fixed32 baseAngle;",
    "    bool    negate = false;",
    "    switch (red.quadrant)",
    "    {",
    "    case 0:  baseAngle = red.angle;          negate = false; break;",
    "    case 1:  baseAngle = kPI_2 - red.angle;  negate = false; break;",
    "    case 2:  baseAngle = red.angle;          negate = true;  break;",
    "    default: baseAngle = kPI_2 - red.angle;  negate = true;  break;  // quadrant 3",
    "    }",
    "",
    "    // Map baseAngle ∈ [0, kPI_2] → LUT index + fractional offset.",
    "    // Integer arithmetic avoids kStep quantization error from storing step as Fixed32.",
    "    const int64_t idx64    = static_cast<int64_t>(baseAngle.value) * kN;",
    "    int32_t       index    = static_cast<int32_t>(idx64 / kPI_2.value);",
    "    if (index >= kN)       index = kN - 1;  // lut has kN+1 entries; access [index, index+1]",
    "    const int64_t frac_num = idx64 - static_cast<int64_t>(index) * kPI_2.value;",
    "    const Fixed32 fraction = Fixed32::FromRaw(",
    "        static_cast<int32_t>(frac_num * Fixed32::Scale64 / kPI_2.value));",
    "",
    "    const FixedUnit sinVal = FixedSinInternal(fraction, static_cast<uint32_t>(index));",
    "    return negate ? -sinVal : sinVal;",
    "}",
    "",
    "FORCE_INLINE FixedUnit FixedCos(Fixed32 x)",
    "{",
    "    static constexpr Fixed32 kPI_2 = Fixed32::FromDouble(1.5707963267948966);",
    "    return FixedSin(kPI_2 - x);",
    "}",
]

output = "\n".join(lines) + "\n"

output_path = "src/Runtime/Math/Public/FixedTrig.h"
os.makedirs(os.path.dirname(output_path), exist_ok=True)
with open(output_path, "w") as f:
    f.write(output)
print(f"Generated {output_path} with {N} entries, range [{values[0]}, {values[-1]}]")
